---
title: "Final Project Proposal"
author: "Shivaram Karandikar"
date: "March 24, 2023"
format:
  html:
    code-fold: true
    embed-resources: true
jupyter: python3
echo: false
---

```{python}
import pandas as pd
import numpy as np
```

```{python}
rest22 = pd.read_csv("C:\\Users\\shiva\\Desktop\\STAT 3255\\final-project-shivaram-k\\data\\DOHMH_New_York_City_Restaurant_Inspection_Results.csv")
```

```{python}
rest22 = rest22.iloc[:, :-6]
```
## Introduction
The topic I have chosen for my final project is to analyze the [DOHMH New York City Restaurant Inspection Results](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j) dataset provided by the City of New York. When you go to a restaurant to eat, you aren't always aware of any possible hygiene/safety issues which might affect your experience. I find this data interesting because it sheds a light on the types of violations that restaurants are getting inspected for and the severity of the violations. There has been research conducted on this topic in the past, especially looking at methods of predicting the grade of a restaurant based on the violations it has received. [Nadler (2014)](https://www.researchgate.net/publication289950328_Using_Logistic_Regression_to_Model_New_York_City_Restaurant_Grades_Over_a_Two-Year_Period) uses logistic regression for this purpose. I would like to continue this research and see if I can find any interesting patterns in the data.

## Specific aims
What are the factors that contribute to a restaurant's grade or score? Do certain cuisines/boroughs have a greater number of violations than others?

## Data description
This dataset contains 27 columns which provide information about restaurants in New York City. Restaurants are inspected by the Department of Health and Mental Hygiene (DOHMH) and are given a grade based on the inspection. The data includes information about specific violations that have occurred, the type of inspection that was done, the corresponding codes for the violations, the type of cuisine, and geographic information (latitude, longitude, borough, etc.). A categorical variable called 'CRITICAL FLAG' denotes whether the inspection found a violation that is likely to contribute to food-borne illnesses. The data is updated daily and contains information from 2014 to the present. I will be using the data from the year 2022 for my analysis. This subset is still very large, containing around 92,000 rows. A majority of the columns have less than 1% missing values, but the Grade and Grade Date columns have around 50% missing values each. Although this would still leave a large enough sample size to work with, I may redirect my analysis to focus on the Score column, the numerical value from which the Grade is derived.

```{python}
rest22.head()
```

## Research design/methods/schedule
My primary interest is in using a multiclass classification model to predict grade. I am planning on using logistic regression, Naive Bayes, or Random Forests to achieve this. I would also like to use NLP methods to analyze the text in the 'VIOLATION DESCRIPTION' column. This could help identify certain themes in the violations that are more common in certain cuisines or boroughs. Nonparametric methods could be used to test these relationships. I would also like to use packages like gmplot or plotly to understand the geographic distribution. 

## Discussion
I believe that the geographic factors will have the strongest influence on the grade of restaurant. New York City does have neighborhoods like Little Italy and Chinatown, so there may be some relation between cuisine and geographic factors in certain cases. There are many factors which influence the grade of a restaurant, so I would not be surprised if the results of my analysis do not match my expectations. A component I feel may be important to include would be economic information for the area, which could help inform the analysis.

## Conclusion
The objective of my analysis is to understand the factors that influence a restaurant's inspection grade by the DOHMH in 2022. This will include classification, hypothesis testing, and geographic visualization of the data.
